---
name: CGI-Application-Session
version: 0.07
author:
  - Cees Hek <ceeshek@gmail.com>
abstract: DEPRICATED in favour of CGI::Application::Plugin::Session
license: perl
requires:
  CGI::Application: 3.21
  CGI::Session: 3.95
  File::Spec: 0
provides:
  CGI::Application::Session:
    file: lib/CGI/Application/Session.pm
    version: 0.07
generated_by: Module::Build version 0.26
