--- #YAML:1.0
name: CGI-Application-Session
version: 0.03
author:
  - Cees Hek <cees@crtconsulting.ca>
abstract: |-
  Plugin that adds session support to CGI::Application
license: perl
requires:
  CGI::Application: 3.21
  CGI::Session: 3.95
provides:
  CGI::Application::Session:
    file: lib/CGI/Application/Session.pm
    version: 0.03
generated_by: Module::Build version 0.23
